# Generated by Django 5.2.9 on 2026-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerequest_hostel_photo_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='hostel_name',
            field=models.CharField(choices=[('Lydia Hall', 'Lydia Hall'), ('Deborah Hall', 'Deborah Hall'), ('Mary Hall', 'Mary Hall'), ('Dorcas Hall', 'Dorcas Hall'), ('Daniel Hall', 'Daniel Hall'), ('Joseph Hall', 'Joseph Hall'), ('Paul Hall', 'Paul Hall'), ('Peter Hall', 'Peter Hall'), ('John Hall', 'John Hall'), ('Joshua Hall', 'Joshua Hall')], max_length=100),
        ),
    ]
